# -*- coding: utf-8 -*-
"""Classroomassignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbNdgSqbl_41DdPWlUSLQ5We1VIKxc6H
"""

! pip install streamlit

# prompt: make a hello world statement and then make a box where the user can input a hello statement back

import streamlit as st

st.write("Hello, world!")

user_input = st.text_input("Say hello back:")

if user_input:
    st.write(f"You said: {user_input}")